[package]
name = "linear_algebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
clap = { version = "4.0.32", features = ["derive"] }
num-traits = "0.2.15"
ron = "0.8.0"
